"""
arnio — Fast CSV processing and data cleaning companion for pandas.

import arnio as ar
"""

from ._version import __version__ as __version__
from .cleaning import (
    CastFailure,
    CastReport,
    cast_types,
    clean,
    clip_numeric,
    drop_constant_columns,
    drop_duplicates,
    drop_empty_columns,
    drop_nulls,
    fill_nulls,
    filter_rows,
    make_column_names_unique,
    keep_rows_with_nulls,
    normalize_case,
    remove_special_chars,
    normalize_unicode,
    normalize_whitespace,
    parse_bool_strings,
    rename_columns,
    round_numeric_columns,
    safe_divide_columns,
    strip_whitespace,
    validate_columns_exist,
)
from .convert import from_pandas, to_pandas
from .exceptions import ArnioError, CsvReadError, TypeCastError, UnknownStepError
from .frame import ArFrame
from .integrations import ArnioPandasAccessor
from .io import read_csv, scan_csv
from .pipeline import pipeline, register_step
from .quality import (
    CleanExplanation,
    CleaningSuggestion,
    CleanStepRecord,
    ColumnProfile,
    DataQualityReport,
    DriftReport,
    ProfileComparison,
    QualityGateIssue,
    QualityGateResult,
    auto_clean,
    check_quality_gates,
    compare_profiles,
    detect_drift,
    profile,
    suggest_cleaning,
)
from .schema import (
    URL,
    UUID,
    Bool,
    CountryCode,
    CurrencyCode,
    Custom,
    Date,
    DateTime,
    Email,
    Field,
    Float64,
    Int64,
    IPv4,
    LanguageCode,
    MACAddress,
    PhoneNumber,
    Regex,
    Schema,
    SchemaDiff,
    SchemaDiffEntry,
    String,
    TimeZone,
    ValidationIssue,
    ValidationResult,
    diff_schema,
    register_validator,
    validate,
    validate_chunked,
)
from .schema_export import schema_from_yaml, schema_to_dict, schema_to_yaml

from_records = ArFrame.from_records

__all__ = [
    # Core class
    "ArFrame",
    "ColumnSummary",
    # I/O
    "read_csv",
    "read_csv_chunked",
    "read_jsonl",
    "read_jsonl_chunked",
    "write_csv",
    "write_json",
    "write_jsonl",
    "read_parquet",
    "write_parquet",
    "scan_csv",
    "sniff_delimiter",
    # Cleaning
    "drop_nulls",
    "drop_columns",
    "select_columns",
    "keep_rows_with_nulls",
    "fill_nulls",
    "validate_columns_exist",
    "filter_rows",
    "replace_values",
    "normalize_whitespace",
    "drop_duplicates",
    "drop_constant_columns",
    "clip_numeric",
    "strip_whitespace",
    "hash_columns",
    "parse_bool_strings",
    "normalize_case",
    "rename_columns",
    "round_numeric_columns",
    "cast_types",
    "make_column_names_unique",
    "clean",
    "safe_divide_columns",
    # Conversion
    "to_pandas",
    "to_arrow",
    "to_polars",
    "from_pandas",
    # Integrations
    "ArnioPandasAccessor",
    # Pipeline
    "pipeline",
    "register_step",
    "unregister_step",
    "get_builtin_step_signatures",
    "list_steps",
    "PipelineContext",
    "LineageReport",
    "reset_steps",
    # Data quality
    "profile",
    "compare_profiles",
    "detect_drift",
    "check_quality_gates",
    "suggest_cleaning",
    "auto_clean",
    "ColumnProfile",
    "DataQualityReport",
    "DriftReport",
    "CleanStepRecord",
    "CleanExplanation",
    "ProfileComparison",
    "QualityGateIssue",
    "QualityGateResult",
    # Schema validation
    "Schema",
    "SchemaDiff",
    "SchemaDiffEntry",
    "Field",
    "ValidationIssue",
    "ValidationResult",
    "validate",
    "validate_chunked",
    "diff_schema",
    "Int64",
    "Float64",
    "String",
    "CountryCode",
    "CurrencyCode",
    "LanguageCode",
    "TimeZone",
    "Bool",
    "Email",
    "URL",
    "PhoneNumber",
    "DateTime",
    # Exceptions
    "UnknownStepError",
    "ArnioError",
    "CsvReadError",
    "JsonlReadError",
    "RemoteReadError",
    "TypeCastError",
    "PipelineStepError",
    "SchemaValidationError",
    "normalize_unicode",
    "Regex",
    "Custom",
    "register_validator",
    "Date",
    "schema_from_yaml",
    "schema_to_dict",
    "schema_to_yaml",
    "save_pipeline",
    "load_pipeline",
    "PipelineSerializationError",
    "encode_categorical",
    "UUID",
    "IPv4",
    "MACAddress",
]
